# Generated by Django 5.1.7 on 2025-05-06 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(default='Maths 2025', max_length=255)),
                ('image', models.ImageField(default='default.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(default='Atoms, Y9, 2025', max_length=255)),
                ('date_field', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.CharField(choices=[('Y9', 'Y9'), ('Y8', 'Y8'), ('Y7', 'Y7')], default='Y7', max_length=255)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('date_field', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.CharField(choices=[('Y9', 'Y9'), ('Y8', 'Y8'), ('Y7', 'Y7')], default='Y7', max_length=255)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.topic')),
            ],
        ),
    ]
